# Shortcuts must be written in the correct order and must be all uppercase
# 1. CTRL (Optional)
# 2. ALT (Optional)
# 3. SHIFT (Optional)
# 4. key (Mandatory)
# example: CTRL+ALT+SHIFT+K
# Special keys:
#   ESC, TAB, CAPS_LOCK, BACKSPACE, ENTER
#   INSERT, DELETE, HOME, END, PAGE_UP, PAGE_DOWN, PAUSE
#   UP, DOWN, LEFT, RIGHT, SPACE


help:
  commands:
    help: Opens command help panel (Subsequent presses cycle through different sort orders)
    key: F1

  help:
    help: Displays keyboard layout help. Cancels when CTRL key is released
    key: CTRL+F1

  about:
    help: Displays information about the editor
    key: CTRL+SHIFT+F1

file:
  new:
    help: Shows file create panel. Allow navigation and completion of path. Creates any folders that do not exist
    key: CTRL+N

  open:
    help: Shows open panel and allows a pattern to be entered to select and open a file. Characters are matched against the relative path. Spaces are wildcards. New files can also be created from here.
    key: CTRL+O

  save:
    help: Save and apply any reformatting modules
    key: CTRL+S

  rename:
    help: Rename or move a file. Opens panel with file path. Make any adjustments and press ENTER
    key: CTRL+M

  switch:
    help: Switch between open files. Like an ALT+TAB window switcher holding down CTRL keeps the list open while pressing TAB cycles through it.
    key: CTRL+TAB

  close:
    help: Closes an open file
    key: CTRL+W

search:
  find:
    help: Find and replace. Uses grep to search the project
    key: CTRL+F

  line:
    help: Move to the line number entered
    key: CTRL+L

  top_left:
    help: Switches to the top left source code window
    key: ALT+1

  top_right:
    help: Switches to the top right source code window
    key: ALT+2

  bottom_left:
    help: Switches to the bottom left source code window
    key: ALT+3

  bottom_right:
    help: Switches to the bottom right source code window
    key: ALT+4

edit:
  undo:
    help: Undoes a keystroke or several if previously entered quickly
    key: CTRL+Z

  redo:
    help: Redoes the previously undone key or keys
    key: CTRL+SHIFT+Z

  cut:
    help: Cuts the selected text and stores it in the clipboard
    key: CTRL+X

  copy:
    help: Copies the selected text to the clipboard
    key: CTRL+C

  paste:
    help: Pastes text from the clipboard at the current cursor position
    key: CTRL+V

  select_all:
    help: Selects all text in current window
    key: CTRL+A

  select_none:
    help: Selects all text in current window
    key: CTRL+SHIFT+A

  delete:
    help: Remove the selected text
    key: DELETE

  del_line:
    help: Remove a while line and move following lines up
    key: CTRL+D

tools:
  complete:
    help: Triggered by pressing TAB after some text. ESC cancels. Press TAB to move to next variable. Same syntax as gEdit. Configured by going to snippets folder and opening the YAML file for the relevant file extension or editing the global.yml file.
    key: TAB

  test:
    help: Switches between code and spec or test. Works for models, views, controllers, helpers, lib, features and steps (maybe)
    key: CTRL+T

  diff:
    help: Switches to a git diff of the file in the current window
    key: CTRL+K

  snippets:
    help: Opens the snippets file(s) related to the current file being edited
    key: CTRL+J

  reload:
    help: Reload configuration files located in config/ and subdirectories
    key: CTRL+Y

  error:
    help: Goto to last error
    key: CTRL+E

main:
  numbers:
    help: Toggle line numbers
    key: CTRL+SHIFT+L

  quit:
    help: Exit editor (ALT+F4 should also work)
    key: CTRL+Q

  cancel:
    help: Cancels (and hides) any open panels and returns to the last focused window
    key: ESC

