# The matcher will find the first language that matches the pattern plus any exists or a bang line
# So if ruby was placed before rubyonrails it would always match and never get to rubyonrails

css:
  pattern: css

cucumber:
  pattern: .feature

haml:
  pattern: .haml

js:
  pattern: .js

html:
  pattern: .html .htm

markdown:
  pattern: .md .markdown

rubyonrails:
  snippets: ruby rails rspec cucumber
  pattern: .rb .rake Rakefile
  exists: config/routes.rb

ruby:
  snippets: ruby rspec cucumber
  pattern: .rb .rake Rakefile Gemfile .gemspec .ru
  bang: ruby

sh:
  pattern: .sh
  bang: bash sh

sass:
  pattern: .sass

sql:
  pattern: sql

xml:
  pattern: xml

yaml:
  pattern: .yaml .yml

