css:
  pattern: css

cucumber:
  pattern: .feature

haml:
  pattern: .haml

js:
  pattern: .js

html:
  pattern: .html .htm

markdown:
  pattern: .md .markdown

ruby:
  pattern: .rb .rake Rakefile Gemfile .ru
  bang: ruby

rubyonrails:
  pattern: .rb .rake Rakefile
  if: script/rails

sh:
  pattern: .sh
  bang: bash sh

sass:
  pattern: .sass

sql:
  pattern: sql

xml:
  pattern: xml

yaml:
  pattern: .yaml .yml

