model:
  match_path: app/models/
  content: |
    class <basename.camelize> < ActiveRecord::Base
      <>
    end

controller:
  match_path: app/controllers/
  content: |
    class <basename.camilize> < ApplicationController
      <>
    end

controller:
  match_path: app/controllers/admin
  content: |
    class <basename.camilize> < AdminController
      <>
    end

