desc: |
  describe ${${ClassName}|'${description}'} do
    ${}
  end

context: |
  context ${${ClassName}|'${description}'} do
    ${}
  end

it: |
  it 'does something' do
    ${}
  end

before: |
  before :each do
    ${}
  end

beforea: |
  before :all do
    ${}
  end

after: |
  before :each do
    ${}
  end

aftera: |
  before :all do
    ${}
  end

